name: scrape
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3,7,11,15,19,23 * * *'
jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
      - name: Generate requirements from pipenv file
        uses: VaultVulp/action-pipenv@v2.0.1
        with:
          command: requirements > requirements.txt
      - name: Install requiremeents
        run: pip install -r requirements.txt
      - name: Run the scraping script
        run: python boplats.py
      - name: Commit and push if content changed
        run: |-
          git config user.name "Automated"
          git config user.email "actions@users.noreply.github.com"
          git add res.js || exit 0
          timestamp=$(date +'%Y-%m-%d %H:%M')
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
